### ISSUE TITLE
encoding issues after conversion to python3

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/supybot-meetbot#3]
after working around #2 , the plugin loads, and i can start a meeting, but trying to do anything else , like a #topic, results in the following error. Its encoding based, so any help here would be awesome.

```
May 24 12:38:36 zodbot.tinystage.test supybot[33358]: ERROR 2021-05-24T12:38:36 Uncaught exception in MeetBot.__call__:
May 24 12:38:36 zodbot.tinystage.test supybot[33358]: Traceback (most recent call last):
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:   File "/usr/lib/python3.6/site-packages/supybot/log.py", line 368, in m
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:     return f(self, *args, **kwargs)
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:   File "/usr/lib/python3.6/site-packages/supybot/irclib.py", line 202, in __call__
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:     method(irc, msg)
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/plugin.py", line 123, in doPrivmsg
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:     M.addline(nick, payload)
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/meeting.py", line 483, in addline
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:     linenum = self.addrawline(nick, line, time_)
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/meeting.py", line 508, in addrawline
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:     nick = self.config.dec(nick)
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/meeting.py", line 105, in dec
May 24 12:38:36 zodbot.tinystage.test supybot[33358]:     return text.decode(self.input_codec, 'replace')
May 24 12:38:36 zodbot.tinystage.test supybot[33358]: AttributeError: 'str' object has no attribute 'decode'
May 24 12:38:36 zodbot.tinystage.test supybot[33358]: ERROR 2021-05-24T12:38:36 Exception id: 0xf4153
```

**Comment by ryanlerch** [comment]
kinda looking for the easiest fix for this one TBH -- dont want to refactor this code.

**Comment by pypingou** [comment]
if it's a string you don't need to decode it.

The question is: do you want to the code to be py3 only or still py2 compatible?

**Comment by ryanlerch** [comment]
python3 only -- thats the easiest thing, right?

**Comment by nphilipp** [comment]
> python3 only -- thats the easiest thing, right?

yes.

**Comment by nphilipp** [comment]
@pypingou's suggestions should be sufficient if you don't care about Python 2. Mind, that there's probably an implicit conversion (from encoded bytes to encoding-less text string) happening somewhere and the traceback looks like the supybot code wants to control that "undecodeable" byte sequences are replaced rather than throw an exception, (what an implicit conversion most likely will do if encountering e.g. ISO-8859 encoded strings).

**Comment by nphilipp** [comment]
What I'm saying is, just be aware that people could trip this—I assume supybot simply catches the thrown exception and logs it like above, but doesn't crash.

**Comment by ryanlerch** [comment]
thanks @nphilipp and @pypingou filed a PR :D
