### ISSUE TITLE
another traceback after converting to python3

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/supybot-meetbot#4]
Just removing the call to to_bytes() here seems to work, but not sure if that is a good idea or not.

```
May 24 12:44:15 zodbot.tinystage.test supybot[33404]: Traceback (most recent call last):
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:   File "/usr/lib/python3.6/site-packages/supybot/log.py", line 368, in m
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:     return f(self, *args, **kwargs)
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:   File "/usr/lib/python3.6/site-packages/supybot/irclib.py", line 202, in __call__
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:     method(irc, msg)
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/plugin.py", line 123, in doPrivmsg
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:     M.addline(nick, payload)
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/meeting.py", line 503, in addline
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:     self.save(realtime_update=True)
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/meeting.py", line 478, in save
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:     return self.config.save(**kwargs)
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/meeting.py", line 177, in save
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:     rawname = self.filename()
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:   File "/usr/lib/python3.6/site-packages/supybot/plugins/MeetBot/meeting.py", line 155, in filename
May 24 12:44:15 zodbot.tinystage.test supybot[33404]:     path = time.strftime(to_bytes(path), self.M.starttime)
May 24 12:44:15 zodbot.tinystage.test supybot[33404]: TypeError: strftime() argument 1 must be str, not bytes
```

**Comment by pypingou** [comment]
just drop the ``to_bytes()`` there.

Same question as in #3 do you want the code to still be py2 compatible?

**Comment by ryanlerch** [comment]
no, no python2 compat is needed
